services:
    tacitus89.rsp.listener:
        class: tacitus89\rsp\event\listener
        arguments:
            - @config
            - @controller.helper
            - @request
            - @template
            - @user
            - %core.root_path%
            - %core.php_ext%
        tags:
            - { name: event.listener }

    tacitus89.rsp.main.controller:
        class: tacitus89\rsp\controller\main_controller
        arguments:
            - @config
            - @controller.helper
            - @pagination
            - @request
            - @template
            - @user
            - @service_container
            - @tacitus89.rsp.operator.ressourcen
            - @tacitus89.rsp.operator.unternehmen
            - %core.root_path%
            - %core.php_ext%

    tacitus89.rsp.operator.ressourcen:
        class: tacitus89\rsp\operators\ressourcen
        arguments:
            - @service_container
            - @dbal.conn
            - %core.table_prefix%

    tacitus89.rsp.operator.unternehmen:
        class: tacitus89\rsp\operators\unternehmen
        arguments:
            - @service_container
            - @dbal.conn
            - %core.table_prefix%

    tacitus89.rsp.entity.betrieb:
        class: tacitus89\rsp\entity\betrieb
        scope: prototype # scope MUST be prototype for this to work!
        arguments:
            - @dbal.conn
            - %core.table_prefix%

    tacitus89.rsp.entity.gebaude:
        class: tacitus89\rsp\entity\gebaude
        scope: prototype # scope MUST be prototype for this to work!
        arguments:
            - @dbal.conn
            - %core.table_prefix%

    tacitus89.rsp.entity.ressource:
        class: tacitus89\rsp\entity\ressource
        scope: prototype # scope MUST be prototype for this to work!
        arguments:
            - @dbal.conn
            - %core.table_prefix%

    tacitus89.rsp.entity.unternehmen:
        class: tacitus89\rsp\entity\unternehmen
        scope: prototype # scope MUST be prototype for this to work!
        arguments:
            - @dbal.conn
            - %core.table_prefix%

    tacitus89.rsp.entity.unternehmen_betrieb:
        class: tacitus89\rsp\entity\unternehmen_betrieb
        scope: prototype # scope MUST be prototype for this to work!
        arguments:
            - @dbal.conn
            - %core.table_prefix%

    tacitus89.rsp.entity.user_ress:
        class: tacitus89\rsp\entity\user_ress
        scope: prototype # scope MUST be prototype for this to work!
        arguments:
            - @dbal.conn
            - %core.table_prefix%
