parameters:
    tacitus89.rsp.tables.ressourcen: %core.table_prefix%rsp_ressourcen
    tacitus89.rsp.tables.ressourcen_bereich: %core.table_prefix%rsp_ressourcen_bereich
    tacitus89.rsp.tables.user_ress: %core.table_prefix%rsp_user_ress
